### ISSUE TITLE
Error when Debugging the Program

### ISSUE THREAD

**Issue by ghost** [carbonsunsu/CarbonRender#1]
![vsdebugconsole_2018-10-10_21-54-06](https://user-images.githubusercontent.com/12240370/46749289-9981e400-ccdf-11e8-8afd-f848f20bdd1b.jpg)

its looks like the program missing something, i checked the directory the renderer mean but its not there :/ any solution?

**Comment by carbonsunsu** [comment]
Yeah, there are some models and textures I didn't upload according to their lisences, if you want a release version whitch can run, I can e-mail it to you.

**Comment by carbonsunsu** [comment]
Yeah, I didn't upload those models and textures I use, you know, because of their lisences. You can add a folder named "Models" and use your own fbx models, and don't forget to modify the scene file. Also you can add a "Textures" folder to add some textures, but the way to add textures to a model is a quite complex for now. I'm working on a material system, adding textures may become much easier after I finish it.

**Comment by carbonsunsu** [comment]
If you just want a release version to run, I can e-mail it to you.

**Comment by ghost** [comment]
sure, if you don't mind. it will be easier for me to replace the the model you use to mine properly
my email was BleedingFaceless@gmail.com by the way

**Comment by tm445741** [comment]
I just want to run the distro, can you email it to me? 1057497918@qq.com
